### PR TITLE
exclude original concerns from classmap

### LINKED ISSUE #6: Ambiguous class resolution because of duplicated traits
> Warning: Ambiguous class resolution, "Spatie\Snapshots\Concerns\SnapshotDirectoryAware" was found 2x: in "vendor/spatie/pest-plugin-snapshots/src/Concerns/SnapshotDirectoryAware.php" and "vendor/spatie/phpunit-snapshot-assertions/src/Concerns/SnapshotDirectoryAware.php", the first will be used.

> Warning: Ambiguous class resolution, "Spatie\Snapshots\Concerns\SnapshotIdAware" was found 2x: in "vendor/spatie/pest-plugin-snapshots/src/Concerns/SnapshotIdAware.php" and "vendor/spatie/phpunit-snapshot-assertions/src/Concerns/SnapshotIdAware.php", the first will be used.

Are these trait duplicates needed for anything? If so I think that this package should use [exclude-files-from-classmaps](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps) to exclude the original files and load the overrides.

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #6

### CODE REVIEW

**Comment by Gummibeer** [comment]
I will test if this change really works and the warning disappears. If so I will publish the PR ready for review.

**Comment by Gummibeer** [comment]
The `*` placeholder/glob could get problematic if a new trait is added that this package does not override. In this case I will revert to the explicit file listing.

**Comment by nunomaduro** [comment]
@Gummibeer Is this pull request ready to be reviewed? Have you tested it?

**Comment by Gummibeer** [comment]
Yes, I've used it via `repositories.github` in a project and the warning disappeared. Reverting to packagist version and the warning got back.
The only thing is if the glob is okay or we should use the explicit list.

**Comment by nunomaduro** [comment]
@Gummibeer Lets go for the explicit list plz.

**Comment by Gummibeer** [comment]
@nunomaduro done, force pushed to the commit before. 🙂

**Comment by faustbrian** [comment]
@nunomaduro could this be merged soon?

**Comment by nunomaduro** [comment]
I will check it tonight.

**Comment by freekmurze** [comment]
Optimistically merging this. Thanks @Gummibeer

**Pull request merged**
